# Generated by Django 5.1.1 on 2024-09-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoins', '0002_alter_exchangerate_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate_date',
            field=models.DateTimeField(),
        ),
    ]
